# Generated by Django 3.2.7 on 2022-09-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_category_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название игры')),
                ('youtube', models.CharField(max_length=255, verbose_name='Ссылка на трейлер')),
                ('system', models.CharField(max_length=255, verbose_name='Системные требования')),
                ('plot', models.TextField(verbose_name='Сюжет')),
                ('effects', models.TextField(verbose_name='Визуальные эффекты')),
                ('sound', models.TextField(verbose_name='Звук')),
                ('features', models.TextField(verbose_name='Функции')),
            ],
            options={
                'verbose_name': 'Обзор игр',
                'verbose_name_plural': 'Обзоры игр',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Загловок'),
        ),
    ]
