# Generated by Django 3.2.7 on 2022-09-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20220926_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка 1'),
        ),
        migrations.AddField(
            model_name='game',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка 2'),
        ),
        migrations.AddField(
            model_name='game',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка 3'),
        ),
    ]
