# Generated by Django 3.2.7 on 2022-09-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_game_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(default=1, unique=True, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
