# Generated by Django 3.2.7 on 2022-10-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_game_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Главная Картинка'),
        ),
    ]
