# Generated by Django 3.2.7 on 2022-10-03 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20221003_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='main_image',
            new_name='image',
        ),
    ]
