# Generated by Django 3.2.7 on 2022-10-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_game_category_game_dev'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game_category',
            options={'verbose_name': 'Категория игры', 'verbose_name_plural': 'Категории игр'},
        ),
        migrations.AlterModelOptions(
            name='game_dev',
            options={'verbose_name': 'Категория платформы'},
        ),
        migrations.AddField(
            model_name='game',
            name='game_category',
            field=models.ManyToManyField(to='blog.Game_category', verbose_name='Категория игры'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_dev',
            field=models.ManyToManyField(to='blog.Game_dev', verbose_name='Платформа'),
        ),
    ]
