# Generated by Django 3.2.7 on 2022-10-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20221023_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_dev',
        ),
        migrations.DeleteModel(
            name='Game_dev',
        ),
    ]
