# Generated by Django 3.2.7 on 2022-10-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20221023_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_dev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название платформы игры')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылка')),
                ('category', models.ManyToManyField(to='blog.Game_category', verbose_name='Категория платформы игры')),
            ],
            options={
                'verbose_name': 'Платформа игры',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='game_dev',
            field=models.ManyToManyField(to='blog.Game_dev', verbose_name='Категория платформы игры'),
        ),
    ]
