# Generated by Django 3.2.7 on 2022-10-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20221026_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game_dev',
            options={'verbose_name': 'Платформа игры', 'verbose_name_plural': 'Платформы игр'},
        ),
        migrations.AddField(
            model_name='game_category',
            name='youtube',
            field=models.CharField(db_index=True, default=1, max_length=255, verbose_name='Ссылка на видео'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game_dev',
            name='category',
            field=models.ManyToManyField(to='blog.Game_category', verbose_name='Категория игр входящие в платформу'),
        ),
    ]
