# Generated by Django 3.2.7 on 2022-10-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20221029_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_category',
            name='youtube',
        ),
        migrations.AddField(
            model_name='game_dev',
            name='youtube',
            field=models.CharField(db_index=True, default=1, max_length=255, verbose_name='Ссылка на видео'),
            preserve_default=False,
        ),
    ]
