# Generated by Django 3.2.7 on 2022-10-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20221029_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_dev',
            name='dev_text',
            field=models.TextField(default=1, verbose_name='Описание платформы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game_dev',
            name='dev_title',
            field=models.CharField(db_index=True, default=1, max_length=255, verbose_name='Заглавие платформы'),
            preserve_default=False,
        ),
    ]
