# Generated by Django 3.2.7 on 2022-10-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20221029_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название платформы')),
                ('text', models.TextField(verbose_name='Текст платформы')),
            ],
        ),
    ]
