# Generated by Django 3.2.7 on 2022-10-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20221029_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_dev',
            name='youtube',
            field=models.CharField(default=1, max_length=255, verbose_name='Ссылка на трейлер'),
            preserve_default=False,
        ),
    ]
