# Generated by Django 3.2.7 on 2022-10-29 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_game_dev_youtube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_dev',
            name='youtube',
        ),
    ]
