# Generated by Django 3.2.7 on 2022-10-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_remove_game_dev_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_category',
            name='youtube',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Ссылка на видео'),
        ),
    ]
