# Generated by Django 3.2.7 on 2022-10-29 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_game_category_youtube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_category',
            name='youtube',
        ),
    ]
