# Generated by Django 3.2.7 on 2022-10-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_remove_game_category_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_category',
            name='text',
            field=models.TextField(default=1, verbose_name='Текст платформы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game_category',
            name='title2',
            field=models.CharField(default=1, max_length=255, verbose_name='Название платформы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game_category',
            name='youtube',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Ссылка на видео'),
        ),
    ]
